version: "3.2"

services:
  maven:
    tty: true
    container_name: ensf409-finalProject-maven-container
    depends_on:
      - mysql
    build:
      context: .
      dockerfile: Dockerfile.maven
    volumes:
      - ".:/app"
      - "/app/target"
    ports:
      - 36295:36295
    environment:
      WAIT_HOSTS: mysql:3306
      WAIT_HOSTS_TIMEOUT: 300
      WAIT_SLEEP_INTERVAL: 30
      WAIT_HOST_CONNECT_TIMEOUT: 30

  react:
    stdin_open: true # docker run -i
    tty: true # docker run -t
    container_name: ensf409-finalProject-react-container
    build:
      context: .
      dockerfile: Dockerfile.react
    volumes:
      - "./frontend/:/app"
      - "/app/node_modules"
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true

  mysql:
    container_name: ensf409-finalProject-database-container
    build:
      context: .
      dockerfile: Dockerfile.database
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_ROOT_PASSWORD: "eNsF409"
      MYSQL_USER: ensf409
      MYSQL_PASSWORD: thisIsACoolEnsf409Password
    ports:
      - "26289:3306"
    expose:
      - "3306"
