version: "3.2"

services:
  maven:
    tty: true
    container_name: ensf409-finalProject-maven-container
    build:
      context: .
      dockerfile: Dockerfile.maven
    ports:
      - 36295:36295
    environment:
      WAIT_HOSTS: mysql:3306
      WAIT_HOSTS_TIMEOUT: 300
      WAIT_SLEEP_INTERVAL: 30
      WAIT_HOST_CONNECT_TIMEOUT: 30
    depends_on:
      - mysql
    command: sh -c "/wait && mvn --no-transfer-progress spring-boot:run"

  react:
    tty: true
    container_name: ensf409-finalProject-react-container
    build:
      context: .
      dockerfile: Dockerfile.react.prod
    ports:
      - 5000:5000
    depends_on:
      - maven

  mysql:
    container_name: ensf409-finalProject-database-container
    build:
      context: .
      dockerfile: Dockerfile.database
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_ROOT_PASSWORD: "eNsF409"
      MYSQL_USER: ensf409
      MYSQL_PASSWORD: thisIsACoolEnsf409Password
    ports:
      - "26289:3306"
    expose:
      - "3306"
