version: "3.2"

services:
  maven:
    tty: true
    container_name: ensf409-finalProject-maven-container
    build:
      context: .
      dockerfile: Dockerfile.maven
    # volumes:
    #   - ".:/app"
    #   - "/app/target"
    ports:
      - 36295:36295

  react:
    # stdin_open: true # docker run -i
    tty: true # docker run -t
    container_name: ensf409-finalProject-react-container
    build:
      context: .
      dockerfile: Dockerfile.react.prod
    # volumes:
    #   - "./frontend/:/app"
    #   - "/app/node_modules"
    ports:
      - 5000:5000
